location/urls.py
from django.urls import path
from . import views
app_name = 'location'
urlpatterns = [
    path('insert', views.create_location, name='insert'),
    path('review/<int:pk>/', views.review, name='review'),
    path('review/<int:pk>/userreview', views.userreview, name='userreview'),
    path('review/<int:pk>/addquestion', views.add_question, name='addquestion'),
    path('review/<int:pk>/<int:qpk>', views.view_answers, name='viewanswers'),
    path('review/<int:pk>/<int:qpk>/addanswer', views.add_answers, name='addanswers'),

    ]

navigator/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from registration import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('registration.urls')),
    path('', include('location.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

registration/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from location import views as loc_views
app_name = 'registration'
urlpatterns = [
    path('', views.home, name='home'),
    path('signup', views.signup, name='signup'),
    path('signin', auth_views.login, name='signin'),
    path('userhome', views.welcome, name='userhome'),
    path('logout', views.logout_view, name='logout'),
    path('edit', views.edit_profile, name='edit'),
    path('addplace', loc_views.home, name='addplace'),
    path('search', views.search, name='search'),
    ]

location/models.py
from django.db import models
from django.utils import timezone
import datetime
from registration.models import User
from django.core.validators import MaxValueValidator, MinValueValidator


class Location(models.Model):
    CATEGORY_CHOICES = [
    ('Home', 'Home'),
    ('Mall', 'Mall'),
    ('Metro station', 'Metro station'),
    ('Tourist spot', 'Tourist spot'),
    ('Food Outlet', 'Food Outlet'),
    ('Hospital', 'Hospital'),
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.TextField(max_length=250, blank=True)
    location = models.CharField(max_length=50, blank=True)
    created = models.DateTimeField('date published', default=timezone.now)
    image = models.FileField(null=True, blank=True)
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES, blank=True)

    def __str__(self):
        return self.location


class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    review = models.TextField(max_length=500, blank=True)
    rating = models.IntegerField(
        validators=[MaxValueValidator(5), MinValueValidator(1)])
    created = models.DateTimeField('date published', default=timezone.now)

    class Meta:
        unique_together = ('user', 'location')

    def __str__(self):
        return "review for " + str(self.location)


class Question(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    question = models.TextField(max_length=200, blank=True)
    created = models.DateTimeField('date published', default=timezone.now)

    def __str__(self):
        return str(self.question) + " @" + str(self.location)


class Answer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer = models.TextField(max_length=200, blank=True)

    def __str__(self):
        return self.answer

location/forms.py
from .models import Location, Review, Question, Answer
from django import forms


class CreatePostModelForm(forms.ModelForm):
    location = forms.CharField(max_length=100, widget=forms.TextInput(attrs={
        'class': 'form-control',
        }))
    description = forms.CharField(required=True, max_length=300, widget=forms.Textarea(attrs={
        'class': 'form-control',
        }))
    class Meta:
        model = Location
        fields = ['location', 'description', 'image', 'category']


class CreateReviewModelForm(forms.ModelForm):
    CHOICES = [(1, '1 star'), (2, '2 star'), (3, '3 star'), (4, '4 star'), (5, '5 star')]
    rating = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect())

    class Meta:
        model = Review
        fields = ['review', 'rating']


class CreateQuestionModelForm(forms.ModelForm):

    class Meta:
        model = Question
        fields = ['question']


class CreateAnswerModelForm(forms.ModelForm):

    class Meta:
        model = Answer
        fields = ['answer']

location/views.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect
from django.http import JsonResponse
from .forms import CreatePostModelForm, CreateReviewModelForm, CreateQuestionModelForm, CreateAnswerModelForm
from django.http import JsonResponse
from .models import Location, Review, Question, Answer
from django.db.models import Avg
from django.db import IntegrityError
from django.views.decorators.cache import cache_control


def home(request):
    form = CreatePostModelForm()
    context = {'form': form}
    return render(request, 'location/index.html', context)


def create_location(request):
    if request.method == 'POST':
        form = CreatePostModelForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('registration:userhome')


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def review(request, pk):
    if request.user.is_authenticated:
        questionform = CreateQuestionModelForm()
        place = Location.objects.get(pk=pk)
        question = Question.objects.filter(location=place).order_by('-created')
        reviews = Review.objects.filter(location=place).order_by('-created')
        rate = Review.objects.filter(location=place).aggregate(Avg('rating'))
        if reviews.count() > 0:
            avg_rating = rate['rating__avg']
        else:
            avg_rating = 0
        form = CreateReviewModelForm()
        return render(request, 'location/review.html', {
            'place': place,
            'reviews': reviews,
            'avg_rating': avg_rating,
            'form': form,
            'questionform': questionform,
            'question': question,
            })
    else:
        return redirect('registration:signin')


def userreview(request, pk):
    if request.method == 'POST':
        form = CreateReviewModelForm(request.POST)
        rating = request.POST.get('rating')

        if form.is_valid():
            try:
                review = form.save(commit=False)
                review.user = request.user
                place = Location.objects.get(pk=pk)
                review.location = place
                review.save()
                flag = 0
            except IntegrityError as e:
                e = "updated record"
                flag = 1
                print(e)
                Review.objects.filter(location=place, user=request.user).update(rating=request.POST.get('rating'), review=request.POST.get('review'))
    rate = Review.objects.filter(location=place).aggregate(Avg('rating'))
    st = '/review/' + str(pk)
    return JsonResponse({'message': str(int(rate['rating__avg'])) + " out of 5",
                            'pk': request.user.pk,
                            'flag': flag,
                            'rating': request.POST.get('rating'),
                            'addhtml': "<h3>by:" + str(request.user) + "</h3><img src=/media/" + str(request.user.image) + " style=height:60;width:60;><p><b>" + request.POST.get('review') + "</b></p>"})


def add_question(request, pk):
    if request.method == 'POST':
        form = CreateQuestionModelForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            location = Location.objects.get(pk=pk)
            post.location = location
            post.save()
        return JsonResponse({
            'question': "<a href='"+str(post.pk)+"'>"+str(request.POST.get('question'))+"</a><br>",
            })


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def view_answers(request, pk, qpk):
    if request.user.is_authenticated:
        question = Question.objects.get(pk=qpk)
        form = CreateAnswerModelForm()
        answers = Answer.objects.filter(question=question)
        return render(request, 'location/answers.html', {'question': question.pk, 'form': form, 'answers': answers, 'questiontext': question.question})
    else:
        return redirect('registration:signin')


def add_answers(request, pk, qpk):
    form = CreateAnswerModelForm(request.POST)
    if form.is_valid():
        print("this is a test")
        post = form.save(commit=False)
        post.user = request.user
        post.question = Question.objects.get(pk=qpk)
        post.save()
        st = '/review/' + str(pk)
    return JsonResponse({'answer': request.POST.get('answer')})

location/templates/location/answers.html
{% extends 'registration/base.html' %}
{% block content %}
{% load static %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
   <link rel="stylesheet" type="text/css" href="{% static 'registration/style.css' %}" />

 <div class="container-fluid">
    
    <ul class="nav navbar-nav">
      
     <li><a href="/userhome" id="branding">
            <div class="logo-copy">
               <h1 class="site-title">Navigator</h1>
               <small class="site-description">World at your fingertips</small>
            </div>
         </a></li>
     
      
      <li>
                <img src="/media/{{ user.image }}" width="60" height="60" name="profilepic"
                onmouseover="profilepic.width=150;profilepic.height=150;" onmouseout="profilepic.width=60;profilepic.height=60;">
             </li>
      <li><a href="{%url 'registration:edit'%}">Edit profile</a></li>
      <li><a href="{%url 'registration:addplace'%}">add place</a></li>
      
    
            
            
             
               <li><a href="{% url 'registration:logout' %}">Logout</a></li>
            </ul>
  
</nav>
</div>
<div class="container">
<h1>{{questiontext}}</h1>
<form method="post" id="id_new_answer">
	{% csrf_token %}
	{{form.as_p}}
	<input type="submit" >
</form>
<div id="answer">
<ul>
{% for answers in answers %}

<li><h4>{{answers.answer}}</h4>
<p>posted by:<b>{{answers.user}}</b></p>
</li>
{% endfor %}
</ul>
</div>
</div>
<script type="text/javascript">
    $(document).on('submit','#id_new_answer',function(e){
      e.preventDefault();
       $.ajax({
         type:'POST',
         url:'{{question}}/addanswer',
         data:{answer:$('#id_answer').val(),
            
         csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
   },success:function(response){
    $('#answer').prepend(response.answer)
   }});
      
    });
     
   </script>
   {% endblock %}

location/templates/location/index.html
<!DOCTYPE html>
<html lang="en" >
<head>
{% load static %}

  <meta charset="UTF-8">
  <title>ADD Location</title>

  <link href='https://fonts.googleapis.com/css?family=Titillium+Web:400,300,600' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
      <link rel="stylesheet" type="text/css" href="{% static 'registration/edit.css' %}" />

  
</head>

<body>
<div class="container-fluid" style="position: sticky;top: 0;z-index: 1;">
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    
    <ul class="nav navbar-nav">
      
     <li><a href="/userhome" id="branding">
            <div class="logo-copy">
               <h1 class="site-title">Navigator</h1>
               <small class="site-description">World at your fingertips</small>
            </div>
         </a></li>
     
      
      <li>
                <img src="/media/{{ user.image }}" width="60" height="60" name="profilepic"
                onmouseover="profilepic.width=150;profilepic.height=150;" onmouseout="profilepic.width=60;profilepic.height=60;">
             </li>
      <li><a href="{%url 'registration:edit'%}">Edit profile</a></li>
      <li><a href="{%url 'registration:userhome'%}">Location Review</a></li>
      
    
            
            
              
               <li><a href="{% url 'registration:logout' %}">Logout</a></li>
            </ul>
          </div>
  
</nav>
</div>
  

  <div class="form">
      <form method="post" id="new_user_form" action="insert" enctype="multipart/form-data">
   {% csrf_token %}
   {{ form.as_p }}

   <button type="submit" class="button button-block">Add Place</button><br>
   
</form>
      
</div> <!-- /form -->
  




</body>

</html>

location/templates/location/review.html
{% extends 'registration/base.html' %}
{% block content %}
{% load static %}
{% load mathfilters %}
<link href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.css" rel="stylesheet"  type='text/css'>
<link rel="stylesheet" type="text/css" href="{% static 'location/style.css' %}" />
<link rel="stylesheet" href="{% static 'location/star.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<div class="container-fluid" style="position: sticky;top: 0;z-index: 1;">
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    
    <ul class="nav navbar-nav">
      
     <li><a href="/userhome" id="branding">
            <div class="logo-copy">
               <h1 class="site-title">Navigator</h1>
               <small class="site-description">World at your fingertips</small>
            </div>
         </a></li>
     
     
      <li>
                <img src="/media/{{ user.image }}" width="60" height="60" name="profilepic"
                onmouseover="profilepic.width=150;profilepic.height=150;" onmouseout="profilepic.width=60;profilepic.height=60;">
             </li>
      <li><a href="{%url 'registration:edit'%}">Edit profile</a></li>
      <li><a href="{%url 'registration:addplace'%}">add place</a></li>
      <li><a href="/userhome">Location reviews</a></li>
      <li><a href="{% url 'registration:logout' %}">Logout</a></li> 
      
    </ul>
    <div class="main-navigation">
            <button type="button" class="menu-toggle"><i class="fa fa-bars"></i></button>
            <ul class="menu" style="background-color:#282726 ;">
              <li><form action="/search" method="POST">
  {% csrf_token %}
  <input type="text" name="search">
  <input type="submit" name="searchbutton" value="Search Place">
</form></li>

               
            </ul>
  </div>
</nav>
</div>

<div id="site-content">
   <header class="site-header">
      <div class="container">
         
         <!-- #branding -->
         
         <!-- .main-navigation -->
         

  <!-- Modal -->
  <div class="modal fade" id="addquestion" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        
        <div class="modal-body">
          
          <form method="post" id="id_new_question">
      {% csrf_token %}
      {{ questionform.as_p}}
      <button type="submit">Add Question</button>
    </form>
        <div id="display_question">

    {% for question in question%}
    <a href="{{question.pk}}" >{{question.question}}</a>
    <br>
    {% endfor %}
  </div>
        </div>
        
      </div>
      
    </div>
  </div>
         <div class="mobile-navigation"></div>
      </div>
   </header>
   <main class="main-content">
      <div class="container">
         <div class="page">
            <div class="breadcrumbs">
               <span>{{place.location}}</span>
               <span class="ask"><a href="#"  data-toggle="modal" data-target="#addquestion">Ask a question?</a></span>
            </div>
            <div class="content">
               <div class="row">
                  <div class="col-md-6">
                     <figure class="movie-poster"><img src="/media/{{place.image}}"></figure>
                  </div>
                  <div class="col-md-6">
                     <h2 class="movie-title">{{place.location}}</h2>
                     
                     <p>{{place.description}}</p>
                     <ul class="movie-meta">
                        <li><strong>Rating:</strong> 
                           <div id="rating">{{avg_rating|floatformat:"2"}} out of 5</div>
                        </li>
                     </ul>
                     <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Add Review:</button>
                  </div>
               </div>
               <!-- .row -->
               

<!-- Modal -->

<div class="modal fade" data-backdrop="" id="myModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <img src="/media/{{request.user.image}}" class="img-circle" style="width: 100;height: 100;"><h4 class="modal-title"><p>{{request.user.first_name}}</p></h4>
            </div>
            <div class="movie-summary">
                         <ul class="movie-meta">
                        
                     </ul>
                     <h2>Add your reviews here</h2>
                     <form  method="post" id="new_review">
                        {% csrf_token %}
                        <span class="star-cb-group">
                        <input type="radio" id="rating-5"  name="rating" value="5"/><label for="rating-5">5</label>
                        <input type="radio" id="rating-4"  name="rating" value="4"  /><label for="rating-4">4</label>
                        <input type="radio" id="rating-3"  name="rating" value="3" /><label for="rating-3">3</label>
                        <input type="radio" id="rating-2"  name="rating" value="2" /><label for="rating-2">2</label>
                        <input type="radio" id="rating-1"  name="rating" value="1" /><label for="rating-1">1</label>
                        <input type="radio" id="rating-0" name="rating" value="0" class="star-cb-clear" /><label for="rating-0">0</label>
                        </span><br>
                        <textarea name="review" id="id_review" cols="40" maxlength="500" rows="10"></textarea><br>
                        <input type="submit" id="first" value="submit">

                     </form>
                     </div>
                     
            
            <div class="modal-footer">
                <button type="button" id="second" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>

</div>
<div class="modal fade" id="ModalRating" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        
        <div class="modal-body">
          <p>Rating inserted</p>
        </div>
        
      </div>
      
    </div>
  </div>

               <div class="entry-content">
<div id="new"></div>
                  {% for reviews in reviews%}
                  <div id="{{reviews.user.pk}}">
                  <h3>by:{{reviews.user}}</h3>
                  <img src="/media/{{reviews.user.image}}" style="height: 60;width: 60;">
                  <p><b>{{reviews.review}}</b></p>
                  {%with y=reviews.rating%}

{% for i in y|rjust:y %}

<span class="fa fa-star checked"></span>
{% endfor %}
{% endwith %}
{% if reviews.rating < 5 %}
{% with x=5|sub:reviews.rating%}
{% for i in "x"|rjust:x %}

<span class="fa fa-star"></span>
{% endfor %}
{% endwith%}
{% endif %}

                  
                    <hr>
                  </div>
                  {% endfor %}
               </div>
            </div>
         </div>
      </div>
      <!-- .container -->
   </main>
   <footer class="site-footer">
      <div class="container">
         <div class="colophon">Copyright 2018 Navigator, Designed by Themezy. All rights reserved</div>
      </div>
      <!-- .container -->
   </footer>
</div>
<!-- Default snippet for navigation -->
<script type="text/javascript">
   $(document).on('submit','#new_review',function(e){
      e.preventDefault();
      $.ajax({
         type:'POST',
         url:'userreview',
         data:{review:$('#id_review').val(),
         rating:$('input:radio[name=rating]:checked').val(),
            
         csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
   },success:function(response){
    var a=response.rating;
    var tag=""
    $('#myModal').modal('hide');
      for(var i=0;i<a;i++)
      {
        tag=tag + "<span class='fa fa-star checked'></span>"
      }
      for(var i=0;i<5-a;i++){
        tag=tag+"<span class='fa fa-star'></span>"
      }
      response.addhtml=response.addhtml + tag + "<hr>"
      $('#rating').html(response.message);
      if(response.flag==1)
      {
      $('#'+response.pk).html(response.addhtml)

     }
     else
     {
      $('#new').html(response.addhtml)
    }
      
$('#ModalRating').modal('show');
setTimeout(function() {
                       $('#ModalRating').modal('hide');
                   }, 1000);
      


      

   }


      });
      
   });
   </script>
   <script type="text/javascript">
    $(document).on('submit','#id_new_question',function(e){
      e.preventDefault();
       $.ajax({
         type:'POST',
         url:'addquestion',
         data:{question:$('#id_question').val(),
         rating:$('input:radio[name=rating]:checked').val(),
            
         csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
   },success:function(response){
    $('#display_question').prepend(response.question)

   }});
      
    });
     
   </script>
   
  
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
{% endblock %}